# Generated by Django 3.0.8 on 2020-08-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
    ]
