# Generated by Django 3.0.8 on 2020-08-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
