# Generated by Django 3.0.8 on 2020-08-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200810_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='imię'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='nazwisko'),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
